### ISSUE TITLE
Faster calculation of page for element

### ISSUE THREAD

**Issue by maesenka** [WegenenVerkeer/atomium#47]
Atomium-jdbc generates a lot of statements such as 'select count(*) from <event-table> where id <= <id>'. For very large event tables these queries are getting very slow.

**Comment by maesenka** [comment]
Relevant background for this discussion https://github.com/WegenenVerkeer/atomium/pull/5

The problem is that the current implementation (and specification) presupposes:

1. that we have an sequence of event entries that are always in the same order (with the oldest at the start, and most recent at the end and )
2.  that the sequence of event entries maps to an integer from 1 to N
3. that “forward” URL paths of the form "<i*pagesize>/forward/<pagesize>" retrieve the <i*pagesize +1> … < (i+1)*pagesize> entries in the sequence, for i >= 0
4. that “backward” URL paths of the form  "<i*pagesize+1>/backward/<pagesize>” retrieve the <(i-1)*pagesize + 1> … < i*pagesize> entries in the sequence, for i > 0
5. 

The immediate, and intended, consequence is that every URL path retrieves exactly <pagesize> elements.

It turns out that clause (2) is problematic in real world implementations. We may want to use sequences, but we can’t because sequences might contain gaps. So every time we want to determine which items to select for given URL, we would have to do a full table scan.

I propose to add a clause (1b):
(1b) event entries may be empty (there is no event at the entry)

This allows us to use “gappy” sequences with the only consequence that in cases of gaps the 'entries' array in the returned page may have less than pagesize elements.

**Impact on implementation:**

AbstractFeedStore and FeedStoreSupport need te be refactored because they assume that we have a contiguous set of records so that by taking one more on the start, and one more on the end we can determine whether there is a next/previous link

**Impact on deployed Atomium Feeds:**

When there has been no gap in the sequence: no impact

When there has been a gap, the feed page URL of a given event may have changed. However, I think the current implementation for the jdbc-store contains a bug. This uses a serial for the ID column. If there are gaps in the ID sequence, then parameter sequenceNr is not in a 1-to-1 correspondence to id column, but then that parameter can’t be used in the where clause of the "select count(*)..”-statement.

**Comment by joachimvda** [comment]
This can cause problems hith concurrent threads. Lets say there is the following sequence of events:

- thread 1 save event (get sequence X)
- thread 2 save event (get sequence X+1)
- thread 2 commit
- client A feed request, returning event X+1, event X is not included in the atom  feed
- thread 1 commit
- client A feed request, result contains both events X and X+1 but as the pointer of processed events points to X+1 (or later) event X is lost.

**Comment by maesenka** [comment]
@joachimvda : you're right. Sequences won't help against this sort of phantom reads.

I agree that the solution you proposed (offline) is the best way to resolve this. This would also leave the specification unchanged. 

An alternative solution would be provide a sort of "indexer" that works on a single thread that constantly calculates the correct sequence number for the events. This might be slightly better in performance, but has the drawback that this might Atomium services stateful.

**Comment by maesenka** [comment]
This is fixed with commit ca177b954cd51e22c2f07806749437c6c322dbe5
